---

- name: "Install base packages"
  package:
    name: "{{ item }}"
    state: "{{ system_packages_state }}"
    update_cache: true
  loop: 
    - "{{ system_packages }}"
    - "{{ system_packages_extra }}"
